Prva verzija - Login, Registracija
AIR-FOI-HR/AIR2024 pull request #1
Opened 2020-11-25 19:12 UTC by KevinBdev

Inicijalni commit za review.

2020-11-26 14:13 UTC, nikolamajcen requested changes
Na temelju promjena u nastavku se nalaze komentari gdje su sugestije i promjene koje je potrebno napraviti.

Osim komentara u kodu, potrebno je još dodati i `.gitignore` datoteku kako biste izbjegli pushanje ~3000 datoteka.
Detalje možete vidjeti ovdje: https://git-scm.com/docs/gitignore

Primjerice, sada je u pull requestu oko 3000 datoteka, a pogledati takav pull request je mukotrpno.
Također, npr. `node_modules` direktorij uopće ne bi trebao biti u repozitoriju, a ima preko 1300 datoteka, dok isto vrijedi i za ostale razne datoteke, npr, `.DS_Store`.

Preporučujem da generirate navedenu datoteku generiranu na https://www.toptal.com/developers/gitignore.
Odaberite okruženja, tehnologije i jezike koje koristite te ih uvrstite u `.gitignore`.

Potrebno je još dodati razne stvari u modul logina i registracije kao što je keyboard handling i text field navigacija.

Također, kao što smo pričali na sastanku, molio bih da se držite naziva brancheva, npr. ovaj se trebao zvati nešto kao `feature/login-and-register`. Govorim ovo radi snalaženja između implementacije feature-a, rješavanja bugfixeva i sl. (npr. `bugfix/wrong-login-response`).

Dodatno;
Prilikom kreiranja pull requesta, molimo da kao reviewere dodate mene i Hrvoja kako bismo navedeni pull request mogli vidjeti te dati potreban review.

2020-11-26 14:13 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Login/LoginViewController.swift
> +        emailTextField.layer.borderWidth = 0
Isto kao i za metodu iznad. I maknuti nepotrebnu liniju `52`.

2020-11-26 14:13 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Login/LoginViewController.swift
> +        passwordTextField.tintColor = .some(UIColor(red:30/255, green:53/255, blue:65/255, alpha: 1))
Isto kao i za metodu iznad te maknuti nepotrebnu liniju `59`.

2020-11-26 14:13 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Login/LoginViewController.swift
> +    }
Maknuti metodu koja ne radi ništa.

2020-11-26 14:13 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Login/LoginViewController.swift
> +        passwordTextField.layer.borderWidth = 0
Primijeniti isto što i za metode iznad.

2020-11-26 14:13 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Login/LoginViewController.swift
> +// Codable json object
Maknuti nepotreban komentar.

2020-11-26 14:13 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Registration/RegistrationViewController.swift
> +class RegistrationViewController: UIViewController {
Dodati `final` modifier.

2020-11-26 14:13 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Registration/RegistrationViewController.swift
> +    @IBOutlet weak var repeatPasswordTextField: UITextField!
Potrebno je maknuti prazne linije između property-a te iste definirati kao `private`.

2020-11-26 14:13 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Registration/RegistrationViewController.swift
> +    }
Maknuti metodu koja ne radi ništa.

2020-11-26 14:13 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Registration/RegistrationViewController.swift
> +    }
Sve navedeno za login vrijedi i za registraciju.

2020-11-26 14:13 UTC, nikolamajcen commented on client/WeatherActivity/Modules/InitialScreens/2nd screen/2ndScreen.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
Promijeniti naziv datoteke u nešto kao `SecondInitialScreen.storyboard`.

2020-11-26 14:13 UTC, nikolamajcen commented on client/WeatherActivity/Modules/InitialScreens/3rd screen/3rdScreen.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
Promijeniti naziv datoteke u nešto kao `ThirdInitialScreen.storyboard`.

2020-11-26 14:13 UTC, nikolamajcen commented on client/WeatherActivity/Modules/InitialScreens/FirstInitialScreen/firstScreen.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
Promijeniti naziv datoteke u nešto kao `FirstInitialScreen.storyboard`.

2020-11-27 10:49 UTC, nikolamajcen requested changes
Some things are good, but some things needs to get fixed.

Also, some comments may be outdated, because I've gone commit-by-commit review because of the number of files.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Models/User.swift
> +import UIKit
`UIKit` ovdje nije potreban, ispravno bi bilo `Foundation`. `UIKit` sadrži komponente sučelja uz sve core elemente.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Models/User.swift
> +    // Additional addition as needed
Komentare možete maknuti.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Models/User.swift
> +    var email: String = "Asd"
Pretpostavljam da je ovo za testiranje, ali preporučam da to ili maknete ili dodate warning kako ne biste zaboravili da to morate maknuti.

Primjer kreiranja warninga;
`#warning("Neka poruka")`

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Models/User.swift
> +    var avatar: String
Vezano za ispravnost podataka, ovdje bi možda više odgovarao naziv `avatarId` ili objekt može ostati ovako, ali pretpostavljam da tip treba biti `Avatar`. Također, ukoliko korisnik nije odabrao avatar, da li će ta vrijednost biti `nil` ili će poprimiti defaultnu vrijednost? U ovisnosti o odluci, ta vrijednost treba ili nemora biti `Optional` (`?`).

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/AutentificationService.swift
> +struct Login: Codable {
Preporuka je da navedenu klasu spremite pod mapu `Models`.
Također, navedena klasa nema nikakvu validaciju, što možete napraviti u samom konstruktoru.

Što se naziva tiče, više konteksta bi dao naziv klase kao `LoginCredentials`, a property-i bi se mogli zvati `email` i `password`.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/AutentificationService.swift
> +struct apiResponse: Decodable {
Naziv klase bi trebao početi velikim slovom.

Također, naziv same klase je previše "širok", jer svaki response je zapravo api response.
Preporuka je da naziv bude nešto kao `AuthResponse` ili sl. jer se zapravo radi o uspješnosti autentifikacije.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/AutentificationService.swift
> +    let logged: Bool?
Property `logged` sam po sebi može biti `true` ili `false`. Iz kojeg razloga je ta vrijednost `Optional`, odnosno koje je stanje u kojem ta vrijednost može biti `nil`?

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/AutentificationService.swift
> +    let deviceToken: String?
Mislim da prilikom autentifikacije trebate slati `sessionToken`, a ne `deviceToken` - a na temelju toga, sessija uvijek mora imati svoj token, pa ta vrijednost ne bi trebala biti `Optional`.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/AutentificationService.swift
> +    func checkCredentials(userEmail email: String, userPassword pw: String, completitionHandler: @escaping (Result<apiResponse,Error>) -> Void) {
Preporuka je da nazive metoda kreirate tako da ce dati određeni kontekst; npr.
```swift
func login(with credentials: LoginCredentials, ...) { ... }
```

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/AutentificationService.swift
> +        let login = Login(userEmail: email, userPassword: pw)
Preporuka je već proslijediti gotov objekt `LoginCredentials`, jer servis ne bi trebao raditi validaciju podataka.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/AutentificationService.swift
> +        AF.request(Constants.baseUrl + "/login",
Preporučujem koristiti metodu `.appending` umjesto operatora `+`.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/AutentificationService.swift
> +                   encoder: JSONParameterEncoder.default).responseData { response in
Možete umjesto metode `responseData` koristiti i `responseJSON` pošto radite sa JSON-om.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Login/LoginViewController.swift
> +        AutentificationService().checkCredentials(userEmail: email, userPassword: password, completitionHandler: { apiResponse in
Preporuka je da ovdje napravite `LoginCredentials` object i ako je objekt uspješno kreiran se radi api poziv. U suprotnome pokazati poruku korisniku.

Što se tiče `AuthenticationService`-a, niste ga kreirali kao varijablu u klasi, tj. unutar samog `LoginViewController`-a je potrebno napraviti; `let authenticationService = AuthenticationService()`
te u ovoj metodi samo zvati `authenticationService.<nazivMetode>...`.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Login/LoginViewController.swift
> +            case .failure(let error):
Pokušajte prvo izlistati success, a onda failure.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Login/LoginViewController.swift
>              case .success(let res):
Koristiti pune nazive, npr. `response`, iako bi bilo bolje staviti naziv o čemu se točnije radi, npr, authResponse, da se dobije kontekst.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Registration/RegistrationViewController.swift
>      }
Nepotreban override metode.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Registration/RegistrationViewController.swift
>              let jsonData = try? JSONSerialization.data(withJSONObject: json)
Navedeno je potrebno promijeniti na temelju komentara u loginu.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Registration/RegistrationViewController.swift
> +    }
Iskreno, ne shvaćam ideju iza ovog, pa bih samo molio objašnjenje u komentaru :)

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/RegistrationService.swift
> +class RegistrationService {
Generalno niste trebali, ali može ostati da imate dva servisa :+1:

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/RegistrationService.swift
> +    func registrateNewUser(userData user: User, onSuccess: @escaping (registrationResponse)->Void, onFailure: @escaping (Error)->Void) {
Mislim da bi naziv metode `register(...)` bio dovoljan pošto se podrazumijeva da registrirate novog usera.

Kada registrirate usera, ideja je da imate objekt npr. `RegisterCredentials` ili nešto slično, pošto samog usera nemate (barem ne cijelog) niti u formi dajete sve informacije (npr. deviceToken).

U loginu koristiti `Result` pattern umjesto dva completiona (success i failure).  Preporuka je odlučiti se za jedno od toga, pa usuglasite koje ćete koristiti. 

P.S. Preporuka je pisati `success` i `failure` umjesto `onSuccess` i `onFailure`.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/RegistrationService.swift
> +        AF.request(Constants.baseUrl + "/registration",
Isto kao i kod logina; `.appending`.

2020-11-27 10:49 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/RegistrationService.swift
> +}
Mislim da bi rezultat response-a također trebao biti `AuthSession` odnosno da vratite `sessionToken`.
Realno, ukoliko dobijete taj response, trebali bi automatski imati `success`, pa vam taj property nije niti potreban.

A za errore da generalno kreirate model koji ćete uvijek koristiti, npr;

```swift
struct ErrorResponse: Decodable {
    let errorMessage: String
}
```

2020-12-01 17:54 UTC, nikolamajcen requested changes
I u ovom slučaju sam išao raditi review commit po commit zbog velikog broja datoteka, pa će možda neki komentari biti duplicirani.

Također, kod prezentiranja prozora imate dupliciranje prilikom svake nove prezentacija zaslona (slika u prilogu) te ćemo o tome popričati tijekom sastanka.

![Screenshot 2020-12-01 at 18 49 41](https://user-images.githubusercontent.com/11491550/100777842-9a69b880-3406-11eb-87ab-6d3c3d3d86ce.png)

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Common/ErrorHandling/RegistrationValidator/RegistrationValidator.swift
> +    }
Generalno bi se ovo dali napisati na razne načine, međutim, mislim da bi bilo bolje kad bi to raspisali kao manje validatore. Npr. ukoliko ćete trebati validirati email ili password na login ekranu, morat ćete raditi login validator.
Također, vrlo je lako zaboraviti pozvati jednu od metoda za provjeru.

Moja preporuka je npr. kreirati više validatora:
* `TextValidator`
* `EmailValidator`
* `PasswordValidator`
* `ComparisonValidator`

Na taj način, svaki validator možete iskoristiti na više mjesta, npr. `PasswordValidator` se može ponovno koristiti na više mjesta bez kreiranja više klasa.

Primjer:
```swift
// Implementacija (svako mora u svoj file)

protocol Validator {

    /// Returns `true` if provided value is valid.
    func validate() -> Bool
}

class EmailValidator: Validator {

    let value: String

    init(value: String) {
        self.value = value
    }

    func validate() -> Bool {
        // Logika validacije
        // ..
        // Ovo je primjer.
        return !value.isEmpty
    }
}

class ComparisonValidator: Validator {

    let values: [String]

    init(values: [String]) {
        self.values = values
    }

    func validate() -> Bool {
        return Set(values).count == 1
    }
}

// Primjer korištenja:

let validator1: Validator = EmailValidator(value: "ana@mail.com")
let isValid1 = validator1.validate()

let validator2: Validator = ComparisonValidator(values: ["password1", "password1"])
let isValid2 = validator2.validate()
```

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Registration/RegistrationViewController.swift
> +        if(!registrationValidator.isValidPasswordLength()){
Preporuka je svaki field testirati u posebnoj metodi, a da svaka metoda brine o validaciji svojeg fielda i vrati npr. `Bool`.
Npr.:
```swift
func isFirstNameValid(value: String) -> Bool {
    // Implementacija
}
...
```

I naravno, preporuka je za svaki field koristiti potreban validator (spomenuto ranije).

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Registration/RegistrationViewController.swift
> +        if(!registrationValidator.isValidPasswordLength()){
Ideja iza svega je da imate manje izolirane metode gdje svaka radi svoj dio posla.
Jer je onda lakše riješavati greške, npr. ako je greška kod validacije emaila, gleda se samo email validator ili metoda `isEmailValid(value:)`.

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Registration/RegistrationViewController.swift
> +        self.performSegue(withIdentifier: "toRegisterCompletion", sender: self)
Potrebno je kreirati metodu koja će definirati navigaciju, kao što je kreirano za npr. `.home` za metodom `navigate(to:)`.

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/LoginService.swift
> +    func checkForToken(token SessionToken: String, success: @escaping (TokenCheckResponse) -> Void, failure: @escaping (Error) -> Void) {
`SessionToken` treba biti `sessionToken` tj. početi malim slovom.

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/LoginService.swift
> +                   parameters: ["sessionToken": SessionToken],
Ovo je dictionary, pošto je jednostavan neka ostane, ali inače bi to trebao biti objekt (Decodable).

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Login/LoginViewController.swift
> +    let keychain = KeychainSwift()
Nije preporučljivo direktno koristiti vanjski dependancy.
Naime, ukoliko se metode ili korištenje vanjske biblioteke promijeni, a koristite tu biblioteku direktno, morat ćete na n mjesta u aplikaciji raditi promjene.

Umjesto toga, preporuka je napraviti wrapper oko te biblioteke te definirati samo metode koje su potrebne. Na taj način se lokalizira vanjski dependancy te će eventualne promjene biti lakše riješiti.

Npr.:

```swift
enum SecureStorageKey: String {
    ....
}

class SecureStorage {

    let keychain = KeychainSwift()

    func save(value: String, key: SecureStorageKey) {
        keychain.set(value, key: key.rawValue)
    }
}
```

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Login/LoginViewController.swift
> +            self.keychain.set(apiResponse.sessionToken, forKey: "sessionToken")
Također, kao što smo pričali, bit će potrebno kreirati `SessionManager` klasu koja će se brinuti o spremanju podataka o sesiji. To možemo proći tokom sutrašnjeg sastanka, ali ideja je da preko te klase radite operacije tj. promjene u sesiji.

Nije preporučljivo direktno spremati ili mijenjati podatke direktno putem vanjske biblioteke, nego npr. pomoću session managera, koji koristi wrapper oko `KeychainSwift` klase.

Npr.:

```swift
class SessionManager {

    // MARK: - Public properties

    let static shared = SessionManager()

    // MARK:  - Private properties

    private let secureStorage = SecureStorage()

    // MARK: - Public methods

    func saveToken(_ value: String) {
        secureStorage.save(value, SecureStorageKey.sessionToken)
        // ili kraće
        secureStorage.save(value, .sessionToken)
    }
}

// Korištenje:
SessionManager.shared.saveToken("dnj1k3jne32")
```

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Login/LoginViewController.swift
> +        if let sessionToken = keychain.get("sessionToken") {
Također, ovdje će se koristiti `SessionManager` pa ćete to "čišće" moći saznati je li korisnik logiran ili ne, npr:

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Login/LoginViewController.swift
> +            self.keychain.set(apiResponse.sessionToken, forKey: "sessionToken")
Također, preporuka je koristiti wrapper, a ne direktno vanjski dependancy.

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Models/RegistrationUser.swift
> +class RegistrationUser: Codable {
Zašto vam je ovo klasa, dok je na drugim mjestima korišten `struct`?

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Models/RegistrationUser.swift
> +    static let registrationUser = RegistrationUser()
Zašto je ovo singleton?

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Models/RegistrationUser.swift
> +    var avatar: Int?
Da li ove vrijednosti mogu biti optional kod registracije korisnika (npr. prema backendu)?

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Registration/RegistrationCompletionViewController.swift
> +        super.viewDidLoad()
Ukoliko metoda ne implementira nikakvu logiku, `override` metode je nepotreban.

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Application/SceneDelegate.swift
> +
Nije handlan case kada nema tokena.

2020-12-01 17:54 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Registration/RegistrationCompletionViewController.swift
> +
O ovome popričamo sutra, jer koristite `UIScrollView` i unutar toga elemente, a definirate ih pomoću tagova.

2020-12-01 20:45 UTC, KevinBdev commented on client/WeatherActivity/Common/Networking/Models/RegistrationUser.swift
> +    var avatar: Int?
Sličan komentar bio je negdje gore. Trenutna implementacija je 
```
var email: String
var firstName: String
var lastName: String
var username: String?
var password: String
var avatarId: Int?
```
Plus naravno init sa svim parametrima
Razlog tome je što na prvom screen-u inicijaliziramo objekt (a na prvom screenu imamo samo podakte vezane uz email, firstname, lastname i password)
Te takav (poluprazan) objekt saljemo u drugi VC gdje još dodajemo username i avatar.
Sad ako je to krivi pristup, promijenit će se.

2020-12-01 21:10 UTC, KevinBdev commented on client/WeatherActivity/Common/ErrorHandling/RegistrationValidator/RegistrationValidator.swift
> +    }
TODO...

2020-12-01 21:18 UTC, KevinBdev commented on client/WeatherActivity/Common/ErrorHandling/Alerter/Alerter.swift
> +}
TODO...

2020-12-02 15:26 UTC, nikolamajcen approved these changes
Approvam ovaj PR da možete raditi svatko na svojem branchu druge funkcionalnosti, a kako smo dogovorili, sitne promjene će se raditi u drugom branchu.

2020-12-02 15:26 UTC, nikolamajcen commented on client/WeatherActivity/Modules/Login/LoginViewController.swift
> +            if(!apiResponse.sessionToken.isEmpty) {
Mislim da vam uopće ne treba `if`, jer ako dobijete success sa backenda, znači da ste dobili `sessionToken` koji vam treba.

2020-12-02 15:26 UTC, nikolamajcen commented
Možete mergeati kad ste spremni 🎉

2020-12-02 15:34 UTC, merged