Feature/add activity/location details
AIR-FOI-HR/AIR2024 pull request #2
Opened 2020-12-07 13:31 UTC by KevinBdev

Kreiram pull request u svrhu dobivanja feedback-a kako bi se lakše otklonile greške koje su već sada implementirane te da se ne ponavljaju tijekom narednih implementacija novih stvari. Dizajnerski aplikacija nije uređena. Od bitnijih funkcionalnosti: traženje location premissiona od usera, dohvat trenutne loakcije (klik na button - slika lokacije), mogućnost traženja lokacija te istovremeno sugeriranje lokacija u dropdown-u, custom odabir lokacije, klikom na mapu kreira se map point (uz sve funkcionalnosti također je map point dodan + zoom na mapi). 
Fali još recent locations (samo prikaz temeljen na SQL upitu - ostavljeno za kasnije) i next+previous button (nakon implementacije jedinstvenog dizajna za njih i kreiranje flow managera)

2020-12-09 21:08 UTC, hhrvoic requested changes
**Aplikacija se ne da runnati**. Morao sam lupiti pod install da se instalira ovaj novi pod: `CHDropDownTextField`. Tek tada sam mogao pokrenuti app. Kada pokrenem app prikaže se location screen, no kada odaberem nešto iz dropdowna to se ne prikaže na mapi (vidi video koji sam stavio u zipu). Isto tako, kad pritisnem na current location button treba mu preko 10s da postavi pin lokaciju, to mi se čini predugo. Komentirao sam alternativu.

Predlažem da napraviš pod install prilikom fixanja PR-a.

[RPReplay_Final1607546783.MP4.zip](https://github.com/AIR-FOI-HR/AIR2024/files/5668653/RPReplay_Final1607546783.MP4.zip)

2020-12-09 21:08 UTC, hhrvoic commented on client/WeatherActivity/Modules/AddActivity/LocationDetails/LocationDetailsViewController.swift
> +        locationManager.requestLocation()
Probaj iskoristiti `startUpdatingLocation` umjesto `requestLocation` i kad dobiješ kolaciju u CLLocationManagerDelegate metodi ispod samo pozovi `stopUpdatingLocation`.

https://www.reddit.com/r/iOSProgramming/comments/53u9sz/better_practice_for_requesting_location/

2020-12-09 21:11 UTC, hhrvoic commented
Također, skužio sam da još uvijek nije dobar gitignore, naziv filea je krivi (fali točka ispred, odnosno treba se zvati `.gitignore`)

2020-12-10 07:17 UTC, KevinBdev commented on client/WeatherActivity/Application/SceneDelegate.swift
> +//        if let sessionToken = SessionManager.shared.getToken() {
Da, samo iz tog razloga

2020-12-10 07:57 UTC, KevinBdev commented on client/WeatherActivity/Modules/AddActivity/LocationDetails/LocationDetailsViewController.swift
> +            locationTextField.dropDownTableVisibleRowCount = 3
Možda zbog imena funkcije? Ukratko, ovo koristim kako bih prikazao dropdown samo kada su barem 3 charactera unešena od strane korisnika, tako mi se činilo zanimljivije iz razloga što kad user unese prvo slovo dolazi velik broj sugestija koje opće nisu logične (moje mišljenje), pa sam stavio event na praćenje promjena u textfieldu, te ako se nalazi taj broj charactera drop down se pokaze / suprotno isto vrijedi.

2020-12-14 22:33 UTC, hhrvoic reviewed
Lokacija i dropdown sad rade očekivano 🎉 Još treba ispraviti nazivlje modela.

Dodatno, ako ne želiš da ti na manjim uređajima mapa bude spljoštena (trenutno će tako raditi) stavi content screena u scroll view i odredi neki razumnu veličinu mapi (može biti neka vrijednost fixna, tipa 400 pointova ili može biti relativna u odnoosu na veličinu ekrana, npr. 0.5 * veličina root view-a.

2020-12-14 22:33 UTC, hhrvoic commented on client/WeatherActivity/Modules/AddActivity/LocationDetails/LocationDetailsViewController.swift
> +        setupDropDown()
Nice!

2020-12-14 22:33 UTC, hhrvoic commented on client/WeatherActivity/Modules/AddActivity/LocationDetails/LocationDetailsViewController.swift
> +        dropDown.bottomOffset = CGPoint(x: 0, y:(dropDown.anchorView?.plainView.bounds.height)!)
Force unwrap, pisati defenzivniji kod (kod koji se ne crasha u slučaju da ne postoji dropDown.anchorView, odnosno height koji proizlazi iz njegovog plainView-a). Npr. ovdje možeš iskoristiti [coalesce](https://www.hackingwithswift.com/example-code/language/what-is-the-nil-coalescing-operator) operator tako da uzmeš ili vrijednost is dropDown.anchorView-a ili ako on ne postoji uzmeš neku defaultnu vrijednost, npr. 0.0. što bi u prijevodu značilo ne settaj offset ako ne postoji ovaj dropdown view.  
```
let yOffset = dropDown.anchorView?.plainView.bounds.height ?? 0.0
dropDown.bottomOffset = CGPoint(x: 0, y: yOffset)
```

Drugi bi bio način da napraviš guard ili if let (ovdje ima više smisla if let) gdje samo u slučaju da vrijednost postoji settaš offset.

```
if let yOffset = dropDown.anchorView?.plainView.bounds.height { 
     dropDown.bottomOffset = dropDown.bottomOffset = CGPoint(x: 0, y: yOffset)
}
```

2020-12-16 09:56 UTC, KevinBdev commented
t

2020-12-16 21:33 UTC, merged