PR za Home screen funkcionalnosti
AIR-FOI-HR/AIR2024 pull request #4
Opened 2020-12-08 12:05 UTC by filipovicf2105

* dodan ListView za aktivnosti i povezan za Home screenom,
* API poziv za dohvaćanje korisnikovih aktivnosti te prikaz istih.

Potrebno dodati, tj. konfigurirati sliku kategorije aktivnosti, a kako iste još nismo dovršili, trenutno stoji avatar kao placeholder.

2020-12-10 11:59 UTC, hhrvoic approved these changes
1. Registracija se crasha 
2. Aktivnosti se ne prikazuju - u konzoli dobijem error:

> Error while getting activities: keyNotFound(CodingKeys(stringValue: "data", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"data\", intValue: nil) (\"data\").", underlyingError: nil))

Response sa servera ne matcha modelu definiranom u appu pretpostavljam :) 

3. Posljedica 2) - infinite loading - error se treba pokriti na način da se sakrije loading i pokaže neki  error UI (bio to alert, neki view na home-u, bilo što, samo da korisnik zna da je došlo do errora).

2020-12-10 11:59 UTC, hhrvoic commented on client/WeatherActivity/Common/Networking/Services/ActivityService.swift
> +                    let jsonData = try JSONDecoder().decode(ActivitiesResponse.self, from: data)
Mislim da je ActivitiesResponse kao wrapper struct/envelope nepotreban. Ruta na backendu treba vraćati array i ovdje bi se samo dekodiralo na način na koji sam predloožio na Slacku.
`JSONDecoder().decode([Activities].self`

2020-12-10 11:59 UTC, hhrvoic commented on client/WeatherActivity/Modules/Home/HomeViewController.swift
> +                print("Error while getting activities: \(error)")
Sakriti loading i handleati error kako ste se već dogovorili (alert/neki error UI na home screenu)

2020-12-10 12:00 UTC, hhrvoic requested changes
Slučajno approveao na prošlom komentaru. :)

2020-12-10 13:50 UTC, filipovicf2105 commented on backend/app.js
> +// app.use(function(req, res, next) {
Zato jer sam isprobavao neke stvari (za koje ni sam nisam siguran zašto) i naravno da sam na kraju zaboravio odkomentirati. x)

2020-12-10 23:27 UTC, filipovicf2105 commented
Problem sa registracijom riješimo u bugfix branchu koji dolazi.

2020-12-14 22:50 UTC, hhrvoic requested changes
Super posao oko stanja na samom view-u.

Par komentara oko referenciranja delegata na loose-ly coupled način, delegiranje u iOS-u se radi putem protokola (možeš zamisliti kao interface Javi = listeneri, protocol ~= interface, delegate ~= listener :)). 
Kad se to popravi možemo umergeati 🎉 

Jedan lijepi članak o delegationu:
https://www.swiftbysundell.com/articles/delegation-in-swift/

2020-12-14 22:50 UTC, hhrvoic commented on client/WeatherActivity/Common/Views/ActivityListView/ActivityListView.swift
> +    var delegateHomeViewController: HomeViewController?
ActivityListView ne mora znati tko ga koristi, odnosno tko mu je delegat, što ako ovaj view želiš iskoristiti npr. na ProfileViewControlleru (karikiram)? Delegate pattern se obično komunicira preko interfacea/protokola.

Dakle, napraviti protokol u kojemu ćeš definirati metode od ActivityListView-a, npr. da je user stisnuo refresh akciju isl. U tom slučaju svaki view može reagirati na svoj način na akcije koje se događaju na ActivityListView-u.  

Dakle, negdje izvan definicije view-a možeš definirati protokol: 

```
protocol ActivityListViewDelegate {
    func didPressReloadAction()
}
```

Kod deklaracije delegata, umjesto `delegateHomeViewController` samo pišeš `delegate`.

2020-12-14 22:50 UTC, hhrvoic commented on client/WeatherActivity/Common/Views/ActivityListView/ActivityListView.swift
> +    var delegateHomeViewController: HomeViewController?
Isto tako, pazi da staviš da je delegat `weak` varijabla, zasad nije toliko bitno, čisto da ne dođe do tzv. retain cycle-a u memoriji i nepredviđenog ponašanja.

2020-12-16 21:46 UTC, hhrvoic approved these changes
Sad je sve ok, treba razriješiti konflikte s glavnim branchom, tada je spremno za merge 👍

2020-12-17 18:00 UTC, merged