Feature/add activity/final details
AIR-FOI-HR/AIR2024 pull request #5
Opened 2020-12-08 18:40 UTC by bbalogovi

Kreiran pull request u svrhu feedback-a vezano za dizajn i logiku hendlanja.

Kreirano:
- osnovna funkcionalnost
- UI za posljednji storyboard kod kreiranja aktivnosti
- CollecitionView za supportedWeathers
- ikonice za supportedWeathers i ilustracije za indoor outdoor aktivnosti
- Assets images organizirane u foldere prema funkciji

Fali: 
- dohvaćanje podataka aktivnosti sa prijašnjih screen-ova
- spremanje aktivnosti (nakon kreiranja flow managera)

2020-12-10 20:23 UTC, nikolamajcen requested changes
Reviewan je samo kod, bez pokretanja aplikacije pošto backend još nije deployan.

2020-12-10 20:23 UTC, nikolamajcen commented on client/WeatherActivity/Application/SceneDelegate.swift
> +                let homeViewController = UIStoryboard(name: "Login", bundle: nil).instantiateViewController(withIdentifier: "LoginViewController") as! LoginViewController
* Preporučil bi ne koristiti force unwrapping u ovom dijelu - izraditi posebnu metodu koja kreira view controller a u suprotnosti možete koristiti i `fatalError` jer to mora proći.
* Koristite isti kod za success i failure, i stoga bi trebalo napraviti pomoćnu metode umjesto dupliciranja koda.
* Nije riješen `else` dio u successu.

Također, moguće je dodati protocol pa da svaki view controller ima negdje definirani storyboard name i storyboard identifier. Također, možete to napraviti i u ekstenziji da bude generički (za storyboard identifier).

Npr.

```swift
class HomeViewController: UIViewController {
}

class ProfileViewController: UIViewController {
}

extension UIViewController {
    
    static var storyboardIdentifier: String {
        return String(describing: self)
    }
}

print(HomeViewController.storyboardIdentifier) // prints "HomeViewController
print(ProfileViewController.storyboardIdentifier) // prints "ProfileViewController"
```

2020-12-10 20:23 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/CollectionViewCell.swift
> +            weatherLabel.textColor = isSelected ? .white : .black
Ovdje nema greške, ali uzmite u obzir da će vam boje morati biti dinamične radi podržavanja dark mode-a, tako da će ovakvo direktno korištenje boja kasnije biti problem.

2020-12-10 20:23 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +    var selectedOutdoorIndoor = 0
Preporučil bi korištenje enuma, da je jednostavnije shvatiti što je selektirano, pa će sukladno tome i naziv varijable mogao biti bolji da daje neki kontekst (npr. `selectedActivityType` ili nešto slično).

Jer npr. iz vrijednosti `0` ne možemo zaključiti o čemu se radi.

2020-12-10 20:23 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +            //proceed with future code
Dodati `#warning()` s porukom.

2020-12-10 20:23 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +    let weatherType = ["Sunny", "Cloudy", "Suncloudy", "Rainy", "Foggy", "Snowy", "Stormy", "Windy"]
Ovakve vrijednosti treba definirati kao enume.

2020-12-10 20:23 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +        UIImage(named: "windy")!
Zaobići force-unwrapping u ovom slučaju, te kasnije kreirati klasu modela ili helper klasu koja će na temelju enuma vratiti i sliku za određeni weather.

Npr.
```swift
enum WeatherType: String {
    case sunny = "sunny"
    case cloudy = "cloudy"
    case rainy = "rainy"
   ...
}

class Weather {

    var type: WeatherType
    var image: UIImage? { UIImage(named: type.rawValue) }
}

ili

class WeatherImageProvider {

    static func image(for type: WeatherType) -> UIImage? {
        return UIImage(named: type.rawValue)
    }
}
```

2020-12-10 20:23 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "Cell", for: indexPath) as! CollectionViewCell
Koristiti `?` te u slučaju faila iskoristiti npr. `fatalError`.
Možda i bolji način je napraviti ekstenziju nad `UICollectionView` koji će na temelju naziva klase definirati `reuseIdentifier`a onda i na taj način promijenite vrijednosti u storyboardu/xibu.

2020-12-10 20:23 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +        let cell = collectionView.cellForItem(at: indexPath)
Na početku provjeriti da li cell postoji preko `guard`-a.

2020-12-10 20:23 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +        let cell = collectionView.cellForItem(at: indexPath)
Fali `guard` na početku.

2020-12-10 20:23 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +            }
Ovo je potencijalni problem pri korištenju jer brišete podatke u kolekciji kroz koju upravo prolazite što može dovesti i do crasha aplikacije jer želite pristupiti objektu koji je obrisan ili indeksu koji više ne postoji.

2020-12-10 20:23 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/CollectionViewCell.swift
> +class CollectionViewCell: UICollectionViewCell {
Naziv klase nije dobar jer ne daje nikakav kontekst. Radi se o komponenti za prikaz tipa vremena, možda `WeatherTypeCollectionViewCell`?

2020-12-10 20:23 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetails.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
Dosta constraintova se krši samo promjenom određenog ekrana (veličine).

![Screenshot 2020-12-10 at 21 22 03](https://user-images.githubusercontent.com/11491550/101825423-df3fce80-3b2d-11eb-8e1c-ace9c921d529.png)

2020-12-11 14:30 UTC, bbalogovi commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +            }
Mislim da je došlo do nesporazuma, ovdje se ne radi o samim podacima iz CollectionView-a već o polju u koje se zapisuju (brišu) selected (deselected) tipovi podržanih vremena.

2020-12-14 14:55 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +            }
Radi se o varijabli `selectedSupportedWeathers`, naime;

```swift
for (index, value) in selectedSupportedWeathers.enumerated() {
    if value == "\(indexPath.item + 1)" {
        selectedSupportedWeathers.remove(at: index)
    }
}
```

U samoj `for` petlji pristupaš i mijenjaš varijablu `selectedSupportedWeathers`, a ta ista petlja ovisi o elementima te varijable.

2020-12-18 23:07 UTC, nikolamajcen requested changes

2020-12-18 23:07 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +    var selectedActivityType = SelectedActivityType.indoor.rawValue
Koristiti `SelectedActivityType.indoor`, ne direktno `rawValue`.

2020-12-18 23:07 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +            sender.selectedOutdoorIndoor(current as! UIButton)
Ne koristiti force unwrap (`!`).

2020-12-18 23:07 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +            sender.deselectedOutdoorIndoor(previous as! UIButton)
Ne koristiti force unwrap (`!`).

2020-12-18 23:07 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +            }
Umjesto da se sprema `rawValue`, bolje je kreirati enum vrijednost `let activityType = SelectedActivityType(rawValue: selectedTag)`.

2020-12-18 23:07 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +            sender.selectedOutdoorIndoor(current as! UIButton)
Ne koristiti force unwrap (`!`).

2020-12-18 23:07 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +            }
Umjesto da se sprema rawValue, bolje je kreirati enum vrijednost `let activityType = SelectedActivityType(rawValue: selectedTag)`.

2020-12-18 23:07 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +    let windy = Weather(type: .windy)
Umjesto navedenog, napraviti array:
```swift
var possibleWeathers: [Weather] {
    [.init(type: .sunny), .init(type: .cloudy), ...]
}
```

2020-12-18 23:07 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/FinalDetails/FinalDetailsViewController.swift
> +        let weatherImages = [sunny.image, cloudy.image, sunCloudy.image, rainy.image, foggy.image, snowy.image, stormy.image, windy.image]
Ovdje iskoristiti array spomenut u komentaru iznad.

2020-12-20 21:41 UTC, nikolamajcen approved these changes
Većina stvari je popravljena pa će PR biti approvan - iako se npr. i dalje koristi force unwrap (`as!`) na nekim mjestima.

👏

2020-12-21 19:45 UTC, merged