Feature/add activity/categories details
AIR-FOI-HR/AIR2024 pull request #6
Opened 2020-12-09 14:03 UTC by pcrncec

Implementirane funkcionalnosti:
- dodan novi stupac u bazu podataka u tablicu activity pod nazivom created_at koji je tipa timestamp i ima defaultnu vrijednost 
- current_timestamp().
- napravljeni upiti za dohvaćanje svih kategorija te posljednje 4 kategorije korisnika na temelju novododanog stupca created_at
- napravljen prikaz svih kategorija u collection viewu + page controlu te omogućeno straničenje
- napravljen prikaz posljednjih 4 kategorija korisnika u horizontal stack viewu te ispis ukoliko korisnik još nema posljednjih kategroija (nema još kreiranih aktivnosti)

Fali:
- mogućnost pretraživanja svih kategorija u collection viewu
- dobivanje posljednjih kategorija za prijavljenog korisnika (trenutno je hardcodiran mail - test3@gmail.com)
- dohvaćanje odabrane kategorije i njezino slanje na idući korak kreiranja aktivnosti
- dodati ikonice za svaku kategoriju (trenutno je samo kreiran label za prikaz naziva kategegorije)

2020-12-10 20:39 UTC, nikolamajcen requested changes
Ima nekoliko stvari za popraviti, ali čini se dobro.
Također, review je napravljen samo pregledom koda pošto backend nije deployan,

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Models/CategoryModels/CategoryResponse.swift
> +    let empty: Bool
Da li postoji opcija da kategorije budu `nil`? Odnosno, da li ima potrebe da ta vrijednost bude `Optional`, pošto se umjesto `nil` može vratiti prazni array.

Također, što točno definira `empty`? Ukoliko se radi da definira ukoliko je `categories` array prazan, onda je taj property redundantan pošto je to moguće saznati putem `categories.isEmpty`.

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Services/CategoryService.swift
> +                    print("er: \(error)")
Maknuti ukoliko nije potrebno.

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesCollectionViewCell.swift
> +    // TODO: add handler for selecting cell
Umjesto `TODO:` dodati:
```swift
#warning("TODO: Add categoryImage outlet")
...
```

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetails.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
Potrebno je sav content screena staviti u `UIScrollView`, pošto se pri manjem ekranu aplikacija trga. 

![Screenshot 2020-12-10 at 21 29 50](https://user-images.githubusercontent.com/11491550/101826206-f4692d00-3b2e-11eb-9f9d-74b2d247d3ee.png)

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +    var allCategories = [String]()
Da li će kategorije biti modeli ili će se koristiti kao `String` kroz aplikaciju?

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +    var emptyResponse: Bool = true
Da li je moguće istu stvar dobiti na temelju `allCategories` ili `recentCategories`? Odnosno, da li je potrebno imati varijablu u koju se sprema stanje da li je `apiResponse` prazan?

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +    var emptyResponse: Bool = true
Ukoliko je to potrebno radi paginacije, možda nazvati to nešto kao `shouldLoadMore` ili nešto slično.

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +        // TODO: get logged user's mail (not hardcoded)
Dodati `#warning()`.

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +                self.emptyResponse = true
Da li je potrebno to provjeravati na ovaj način? Naime, u responseu se dobiva array, koji može dati navedenu informaciju.

Također, optimizacije radi, npr. ako je broj kategorija po stranici npr. 10, a rezultat vrati manje elemenata od 10 (npr. 7), može se zaključiti da ne treba još jedan dodatan poziv koji će vratiti prazan array - tako se smanjuje potreba za dodatnim API pozivom.

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +                self.recentCategories = apiResponse.categories!
Ne koristiti force unwrapping, uvijek je bolje koristiti `guard let ...` ili `if let ...`.

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +            // TODO: move self.updateHorizontalStackView() from this function to viewDidLoad() - currently only works this way
Dodati `#warning()`.

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +            self.allCategories = apiResponse.categories!
Isto kao i gore navedeno za force unwrap.

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +            // TODO: fix bug with page control not recognizing last page and not setting propiate number of pages
Staviti kao `#warning`.

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +            // TODO: move self.updateCollectionView() from this function to viewDidLoad() - currently only works this way
Staviti kao `#warning`.

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "CollectionViewCell", for: indexPath) as! CategoriesCollectionViewCell
Ne koristiti force unwrap. Možete koristiti `guard` a ako ne uspije jednostavno pozvati `fatalError`.

2020-12-10 20:39 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +//        DispatchQueue.main.async {
Obrisati ukoliko nije potrebno.

2020-12-16 20:47 UTC, pcrncec commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +    var allCategories = [String]()
Koristit će se samo kao `String` pošto svaka kategorija ima samo svoj unique naziv i ništa drugo, pa mislim da nema potrebe za modelom.

2020-12-16 20:59 UTC, pcrncec commented on client/WeatherActivity/Common/Networking/Models/CategoryModels/CategoryResponse.swift
> +    let empty: Bool
Složeno je sada uz pomoć categories.isEmpty

2020-12-16 21:01 UTC, pcrncec commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +    var emptyResponse: Bool = true
Maknuta je varijabla emptyResponse.

2020-12-16 21:07 UTC, pcrncec commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +                self.emptyResponse = true
Napočetku nisam bio siguran da se može vratiti prazan array, odnosno koliko je to pouzdano. Izgleda da i preko provjere praznog arraya radi kako treba, pa je to sad promijenjeno.

2020-12-17 09:45 UTC, nikolamajcen commented on client/WeatherActivity/Modules/AddActivity/CategoriesDetails/CategoriesDetailsViewController.swift
> +    var allCategories = [String]()
U redu. Međutim, da li će identifikator kategorije biti jednak nazivu kategorije? 

Ja bih svakako preporučio korištenje enuma, jer na koji način ćete koristiti npr. provjeru kategorija ili njihovo korištenje tipa: `mojaKategorija == "imekategorije`? Preporuka je imati definirane konstante ili enume, a za vas je enum najbolje rješenje u tom slučaju.
```swift
enum Category: String {
    case mojaKategorija = "mojaKategorija"
    ...
}
```

2020-12-18 23:08 UTC, nikolamajcen requested changes
Dodatno riješiti konflikte prije mergeanja.

2020-12-18 23:08 UTC, nikolamajcen commented on client/WeatherActivity/Common/Networking/Models/CategoryModels/CategoryResponse.swift
> +    let categories: [String]
Ovo ne bi trebao biti `[String]`, nego array enuma za sve kategorije.

2020-12-21 20:54 UTC, nikolamajcen approved these changes
Sve ok 👌  Još samo popraviti konflikte, pa kad to riješiš možeš mergeati.

2020-12-24 16:45 UTC, merged